# Generated by Django 3.1 on 2020-08-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=280)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
