# Generated by Django 3.1 on 2020-09-04 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0002_tweet_twitter_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_receive', models.DateTimeField(blank=True, default=None, null=True)),
                ('tweet_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_receive', to='tweet.tweet')),
                ('user_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
