# Generated by Django 3.1 on 2020-09-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_receive',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_flag',
            field=models.BooleanField(default=False),
        ),
    ]
