# Generated by Django 3.1 on 2020-09-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200904_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read_flag',
            new_name='notif_flag',
        ),
    ]
